Compress and tile all test tif rasters
This cuts down on size and fixes an issue where some of the rasters were
causing rasterio to throw an error in some envs. The error:

```
RasterBlockError: The height and width of TIFF dataset blocks must be multiples of 16
```

This has something to do with the tiling, but I could not figure out
what exactly was causing the issue. The completely reencodes them as
valid tiled rasters.